### ISSUE TITLE
Finere understrek på lenker

### ISSUE THREAD

**Issue by macbruker** [navikt/nav-enonicxp-frontend#1163]
Vi har en blanding av border-bottom og underline som stil for understreker på lenker. Den blandingen synes jeg vi skal rydde opp i. Vanlig understrek med fonten vår er litt kraftig, så har utforsket mulighetene for justering. CSS har fått bedre støtte for å tilpasse stilen på understreker, så dette er koden jeg brukte i skjermbildet til nytt forslag.

``` css
a {
    text-decoration: underline;
    text-decoration-thickness: 0.05em;
    text-underline-offset: 0.1em;
}
```

Dagens visning
<img width="374" alt="" src="https://user-images.githubusercontent.com/1032194/205000516-2de89743-90ba-434a-845a-762cdf3dfcf2.png">

Forslag til ny visning
<img width="372" alt="" src="https://user-images.githubusercontent.com/1032194/205001138-dcd86ccf-3943-4305-8bd9-0bf64759bb22.png">
