### ISSUE TITLE
Manglende avstand mellom indikatorer for chat

### ISSUE THREAD

**Issue by macbruker** [navikt/nav-enonicxp-frontend#1361]
Peter Brottveit Bock meldte inn en feil [via #team-personbruker på Slack](https://nav-it.slack.com/archives/C9CJ794PP/p1683715005763009).

![image](https://github.com/navikt/nav-enonicxp-frontend/assets/1032194/9e209bbb-5381-4ad1-8e0a-fd3b85e11f25)

Det mangler luft mellom de to elementene som indikerer status for chat. Feilen kan rettes ved å pakke inn de to status-elementene i en ekstra `<div>` og legge på følgende CSS.

![image](https://github.com/navikt/nav-enonicxp-frontend/assets/1032194/9b2b654c-e02f-4bd6-a251-7fcda417ed30)

```CSS
.example {
    display: flex;
    flex-wrap: wrap;
    column-gap: var(--a-spacing-6);
}
```
